version: '3.8'

services:
  frontend:
    image: studyprodcontainerregister.azurecr.io/frontend:latest
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5193
    depends_on:
      - backend

  backend:
    image: studyprodcontainerregister.azurecr.io/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5193:5193"
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - KEY_VAULT_URL=${KEY_VAULT_URL}