name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v2

    # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to Container Registry
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: studyprodcontainerregister.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Deploy Frontend
    - name: Deploy Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-frontend
        images: studyprodcontainerregister.azurecr.io/frontend:latest

    # Configure Frontend Settings
    - name: Configure Frontend Settings
      run: |
        az webapp config appsettings set \
          --name studyproductivityapp-frontend \
          --resource-group studyproductivity \
          --settings \
            NEXT_PUBLIC_BACKEND_URL="https://studyproductivityapp-backend.azurewebsites.net" \
            WEBSITES_PORT=3000

    # Deploy Backend
    - name: Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-backend
        images: studyprodcontainerregister.azurecr.io/backend:latest

    # Configure Backend Container Settings
    - name: Configure Backend Container Settings
      run: |
        az webapp config container set \
          --name studyproductivityapp-backend \
          --resource-group studyproductivity \
          --docker-custom-image-name studyprodcontainerregister.azurecr.io/backend:latest \
          --docker-registry-server-url https://studyprodcontainerregister.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

        az webapp config appsettings set \
          --name studyproductivityapp-backend \
          --resource-group studyproductivity \
          --settings \
            ASPNETCORE_URLS="http://+:5193" \
            DOTNET_URLS="http://+:5193" \
            WEBSITES_PORT=5193 \
            AZURE_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}" \
            AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}" \
            AZURE_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}" \
            KEY_VAULT_URL="${{ secrets.KEY_VAULT_URL }}"

        az webapp config set \
          --name studyproductivityapp-backend \
          --resource-group studyproductivity \
          --generic-configurations '{"startupTimeLimit": 600}'

    # Restart Apps
    - name: Restart Apps
      run: |
        az webapp restart --name studyproductivityapp-backend --resource-group studyproductivity
        az webapp restart --name studyproductivityapp-frontend --resource-group studyproductivity