name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v2

    # Install Docker Compose Plugin
    - name: Install Docker Compose Plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version

    # Login to Docker Registry
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: studyprodcontainerregister.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and push to ACR
    - name: Build and push containers
      run: |
        docker compose build
        docker compose push

    # Login to Azure (needed for Web App deployment)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy to Azure Web Apps
    - name: Deploy Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-frontend-c7g8fed7c8ebhha4
        images: studyprodcontainerregister.azurecr.io/frontend:latest

    - name: Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-backend-bpc4cxfhctgqgeev
        images: studyprodcontainerregister.azurecr.io/backend:latest