name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v2

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
        docker compose version

    # Login to Docker Registry
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: studyprodcontainerregister.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Login to Azure (needed for Web App deployment)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy to Azure Web Apps
    - name: Deploy Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-frontend
        images: studyprodcontainerregister.azurecr.io/frontend:latest

    - name: Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-backend
        images: studyprodcontainerregister.azurecr.io/backend:latest