name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version

    # Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Login to Docker Registry
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: studyprodcontainerregister.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and push to ACR
    - name: Build and push containers
      run: |
        docker compose build
        docker compose push

    # Login to Azure (needed for Web App deployment)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy to Azure Web Apps
    - name: Deploy Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-frontend-c7g8fed7c8ebhha4
        images: studyprodcontainerregister.azurecr.io/frontend:latest

    - name: Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: studyproductivityapp-backend-bpc4cxfhctgqgeev
        images: studyprodcontainerregister.azurecr.io/backend:latest

    # Optional: Add deployment verification
    - name: Verify Frontend Deployment
      run: |
        echo "Verifying frontend deployment..."
        curl -s -o /dev/null -w "%{http_code}" https://studyproductivityapp-frontend-c7g8fed7c8ebhha4.azurewebsites.net/

    - name: Verify Backend Deployment
      run: |
        echo "Verifying backend deployment..."
        curl -s -o /dev/null -w "%{http_code}" https://studyproductivityapp-backend-bpc4cxfhctgqgeev.azurewebsites.net/health