name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Frontend Tests
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Install Frontend Dependencies
      working-directory: ./FrontEnd
      run: npm install --legacy-peer-deps
    
    - name: Run Frontend Tests
      working-directory: ./FrontEnd
      env:
        NEXT_PUBLIC_VITE_BACKEND_URL: studyproductivityapp-backend-bpc4cxfhctgqgeev.polandcentral-01.azurewebsites.net
      run: npm test

    # Backend Tests
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Run Backend Tests
      run: dotnet test StudyProductivityApp.Persistence.Tests/StudyProductivityApp.Persistence.Tests.csproj

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose-plugin
        docker compose version

    # Login to Docker Registry
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: studyprodcontainerregister.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and push containers
    - name: Build and push containers
      run: |
        docker compose build
        docker compose push